### ISSUE TITLE
Style edit buttons

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/time-bend-web#10]
Vertically center the checkbox and edit icon. Using `margin: auto`, perhaps with `display: flex;` in the parent container, centers the checkbox. This doesn't work for the `IconButton` though. Perhaps @AshtrayShetty could help 😉.

**Comment by AshtrayShetty** [comment]
I want to work on this issue. But currently I'm running into some issues with setting up the environment.

**Comment by neelkamath** [comment]
Which instruction do you get stuck at?

**Comment by AshtrayShetty** [comment]
Never mind. Got it to work. Currently on it
