### ISSUE TITLE
Fix CSS text alignment

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/time-bend-web#26]
<img width="1440" alt="Screen Shot 2020-10-01 at 2 06 11 PM" src="https://user-images.githubusercontent.com/24778804/94787176-9661f000-03ef-11eb-9a52-330b11f3a99f.png">

As you can see, the time (_00:00_) and text (_day start_) are misaligned. Fix the CSS to correctly center them. It should work across desktop, tablet, and mobile screen sizes. [`DayTime.tsx`](https://github.com/neelkamath/time-bend-web/blob/master/src/components/DayTime.tsx) may be the file you need to edit.

**Comment by Ruth-ikegah** [comment]
can i take this up @neelkamath

**Comment by neelkamath** [comment]
Sure! 😄

**Comment by Ruth-ikegah** [comment]
Hi @neelkamath , I checked the page and it seems the issue has been corrected?

![css](https://user-images.githubusercontent.com/62059002/94973282-2a70ac00-0503-11eb-81e5-1f170dfedb92.png)

**Comment by Ruth-ikegah** [comment]
Could you outline the steps to reproduce the bug?

**Comment by neelkamath** [comment]
The issue may be a little difficult to reproduce because the styling has been hardcoded for Chrome. If you open the page in other browsers/platforms, the styling can be off by quite a bit.

Here's a screenshot of the styling working fine on Chrome:
<img width="1440" alt="Screen Shot 2020-10-03 at 6 58 35 AM" src="https://user-images.githubusercontent.com/24778804/94980313-2ade6680-0546-11eb-9f19-25878fc53f23.png">

Here's a screenshot of the styling being noticeably (but not significantly) off on Firefox:
<img width="1440" alt="Screen Shot 2020-10-03 at 6 58 39 AM" src="https://user-images.githubusercontent.com/24778804/94980328-421d5400-0546-11eb-8e83-c097f2f1d93a.png">

Here's a screenshot of the styling being unusable on Safari:
<img width="1440" alt="Screen Shot 2020-10-03 at 6 58 47 AM" src="https://user-images.githubusercontent.com/24778804/94980340-637e4000-0546-11eb-8ed5-ba80cc53730e.png">

**Comment by Ruth-ikegah** [comment]
Ohh yeah I see. This is quite technical for me to take on.

**Comment by neelkamath** [comment]
No issues. Do you want to try, or should I assign this to someone else?

**Comment by Ruth-ikegah** [comment]
Please assign it to someone else. I am sorry for the inconveniences

**Comment by AshrayShetty4** [comment]
can I work on this issue?

**Comment by neelkamath** [comment]
Go ahead 😄
